### PR TITLE
modernize recipe

### PR DESCRIPTION
**Pull request by hmaarrfk**
can be made noarch when https://github.com/conda-forge/futures-feedstock/pull/11 gets pulled in

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
@jakirkham see this PR to understand why I want to make arch dependent versions of pathlib and futures. This package, and likely many others could become noarch.

**Comment by jakirkham** [comment]
Doesn’t `tifffile` have compiled code?

**Comment by hmaarrfk** [comment]
not anymore. See this effort from 1 year ago.

I'm trying to get the dependencies pulled in 1 by one 
https://github.com/conda-forge/staged-recipes/pull/6842

**Comment by jakirkham** [comment]
Ah ok. Sorry I missed that. Thanks for reviving this effort. 🙂

**Comment by hmaarrfk** [comment]
feel free to pull them in ;)

Also, I'm not sure how to create a migrator for libjepeg-trubo? can you create one?

**Comment by jakirkham** [comment]
Can you please raise an issue on `conda-forge-pinning` for that?

**Pull request merged**
