### PR TITLE
Use imagecodecs

### LINKED ISSUE #36: Imagecodecs for full support
I'm not familiar with conda build system, but I think that it will be good to tifffile depends on imagecodecs, not imagecodecs-lite. 

I found way to build Imagecodecs on linux and macos for the purpose of creating wheel: https://github.com/Czaki/imagecodecs

All scripts needed are in `build_utils` 

I can support someone who would like to create such formula, or can try to create it on my own, if got some good tutorial.

### PR DESCRIPTION
**Pull request by ericpre**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #36 and #39.

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
Thanks @ericpre!  Do you want to add yourself under maintainers?

**Comment by ericpre** [comment]
> Thanks @ericpre! Do you want to add yourself under maintainers?

Done!

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Pull request merged**
